server:
  port: 11020
database:
  host: 172.21.62.34
  port: 13306
  name: tx-manage
  username: root
  password: duling@2021!
regist-center:
  ip: 172.21.62.34
  port: 19761
spring:
  application:
    name: tx-manage
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10 #初始化连接大小
      min-idle: 10 #最小空闲连接数
      max-active: 1000 #最大连接数
      query-timeout: 6000 #查询超时时间
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
      filter-class-names: stat
      filters: stat,config
  redis:
    host: 172.21.62.34
    port: 16379
    password: duling@2021!
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000

tx-lcn:
  manager:
    #指定默认密码
    admin-key: 123456
    #注册地址
    host:
    #指定固定端口
    port: 11021
  #TX-LCN记录入库
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
#TX-LCN日志级别
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG
#Eureka注册信息
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 8.136.105.20
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${regist-center.ip}:${regist-center.port}/eureka/
